const  GET_DATA='GET_DATA';
const POST_DATA='POST_DATA';
const PUT_DATA='PUT_DATA';
const PUSH_TODO='PUSH_TODO';
const PUSH_PROGRESS='PUSH_PROGRESS';
const PUSH_DONE='PUSH_DONE';

export default {
    GET_DATA,
    POST_DATA,
    PUT_DATA,
    PUSH_TODO,
    PUSH_PROGRESS,
    PUSH_DONE,
}